datasets:
  - name: 'sapsucker_woods'
    sites: ['SSW']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/USA_Sapsucker/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'bialowieza'
    sites: ['site_223', 'site_205', 'site_187', 'site_245', 'site_181',
            'site_162', 'site_183', 'site_242', 'site_193', 'site_208',
            'site_188', 'site_185', 'site_195', 'site_194', 'site_236']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/Bialowieza/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'hawai'
    sites: ['UHH_S01', 'UHH_S02']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/Hawai/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'coffee_farms'
    sites: ['NES_S01', 'NES_S02']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/Coffee_farms/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'usa_sierra_nevada_forest' 
    sites: ['SNE_001','SNE_002','SNE_003','SNE_004','SNE_005','SNE_006','SNE_007','SNE_008', 'SNE_009',
            'SNE_010','SNE_011', 'SNE_012','SNE_013','SNE_014','SNE_015','SNE_016','SNE_017','SNE_018', 'SNE_019',
            'SNE_020','SNE_021','SNE_022','SNE_023','SNE_024','SNE_025','SNE_026','SNE_027','SNE_028','SNE_029',
            'SNE_030','SNE_031','SNE_032','SNE_033'] 
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/USA_sierra_nevada_forest/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'uk_sussex_countryside'
    sites: ['BA-01', 'BA-02', 'BA-03', 'BA-04', 'BA-05', 'BA-06', 'BA-07',
            'BA-09', 'BA-10', 'BA-11', 'BA-12', 'BA-13', 'BA-14', 'BA-15',
            'BA-16', 'KN-01', 'KN-02', 'KN-03', 'KN-04', 'KN-05', 'KN-06',
            'KN-07', 'KN-09', 'KN-10', 'KN-11', 'KN-12', 'KN-13', 'KN-14',
            'KN-15', 'KN-16', 'PL-01', 'PL-02', 'PL-03', 'PL-04', 'PL-05',
            'PL-06', 'PL-07', 'PL-09', 'PL-10', 'PL-11', 'PL-12', 'PL-13',
            'PL-14', 'PL-15', 'PL-16']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/UK_Sussex_countryside/audio'
    datetime_format: '%Y%m%d_%H%M'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'ecuador'
    sites:  ['PO-07', 'PO-08', 'FS-03', 'FS-13', 'FS-02', 'FS-16', 'FS-04',
              'FS-12', 'PO-10', 'FS-17', 'TE-13', 'PO-11', 'PO-01', 'PO-09',
              'TE-10', 'TE-01', 'TE-09', 'FS-14', 'PO-03', 'PO-13', 'FS-08',
              'FS-10', 'FS-11', 'PO-06', 'TE-08', 'FS-07', 'TE-02', 'TE-05',
              'TE-15', 'PO-02', 'PO-15', 'FS-06', 'TE-06', 'TE-11', 'TE-04',
              'PO-12', 'TE-07', 'FS-01', 'PO-05', 'PO-04', 'TE-03', 'PO-14',
              'FS-05', 'TE-14', 'TE-12']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/Ecuador/audio'
    datetime_format: '%Y%m%d_%H%M'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'risoux'
    sites: ['risoux3']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/dB@risoux/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null
  - name: 'peru'
    sites: ['PER_S01', 'PER_S02', 'PER_S04', 'PER_S05', 'PER_S06', 'PER_S08', 'PER_S10']
    path: '/media/haupert/data/mes_projets_data/nROI/dataset/_02_dataset_for_publication/Peru/audio'
    datetime_format: '%Y%m%d_%H%M%S'
    flim_max: null
    flim_min: null
    tlim_min: null
    tlim_max: null

seed: 1979

# Save directory
save_dir: '../results/'

# audio files extension by default
audio_extension: '.wav'

# annotations
annotations_filename: 'species_gt_15min.csv'
ground_truth: 'species_richness' # species_richness pseudo_species_total_abundance pseudo_species_inv_simpson

# signal processing: spectrogram
channel: 'left'
sampling_frequency: 44100
n_fft: 1024
hop_length: 512
window: 'hann'

# parameters to compute the alpha indices
mode_env: 'fast'
Nt: 512
gain: 16
sensibility: -35
vadc: 2
p_ref: 0.00002
deltaT: 1
dB_threshold: 3
reject_duration: 0.01

flim_low: [0, 2000]
flim_mid: [2000, 10000]
flim_hi:  [10000, 20000]

# parameters to compute the nROI and aROI
min_event_duration: 0.1
max_event_duration: null
min_freq_bw: 100
max_freq_bw: null
remove_rois_flim_min: 50
remove_rois_flim_max: null
fusion_rois: [0.05, 100] 
remove_rain: true
max_ratio_xy: 10
seed_level: 16
low_level: 6

# correlation
optimized: false
remove_clipping_audio: true
correlation_method: 'spearman' # spearman pearson
n_bootstrap: 1000

list_indices: ['ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 
              'BGNt', 'SNRt', 'M', 'Ht', 'ACTtFraction', 'ACTtCount',
              'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 
              'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NP', 'LEQf', 'BGNf', 'SNRf',
              'Hf', 'H', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 
              'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 
              'BioEnergy', 'BIO', 'ROU','ADI', 'AEI', 'LFC', 'MFC', 'HFC', 
              'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 
              'EVNspCount', 'TFSD','H_Havrda', 'H_Renyi', 'H_pairedShannon', 
              'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'nROI', 'aROI']

# regression
percent_train: 0.75

# list_indices_multiple_regression: ['ADI', 'Hf', 'EPS_KURT', 'ECU', 'MEANf', 'BIO', 
#                                   'AGI', 'NP', 'nROI', 'ACI', 'TFSD', 'SNRf','LFC']

# list_indices_multiple_regression: ['ADI', 'KURTf', 'EPS_KURT', 'ECU', 'BioEnergy', 'BIO', 
#                                   'ACTspMean', 'NP', 'nROI', 'ACI', 'TFSD', 'SNRf','LFC']

list_indices_multiple_regression: ['nROI', 'ACTspMean', 'NP', 'TFSD', 'BIO', 'ACI', 'LFC', 'NDSI', 
                                    'ECU', 'SNRf', 'EPS_KURT', 'EVNtCount', 'ADI', 'H', 'MEANf'  ]